import { Movie, UserRating, UserCommunity } from "@shared/schema";

export const mockMovies: Movie[] = [
  {
    id: "1",
    title: "Quantum Nexus",
    year: 2024,
    genre: "Action",
    rating: 8.1,
    synopsis: "A mind-bending action thriller that explores the boundaries between reality and simulation.",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Christopher Chen",
    cast: ["Marcus Johnson", "Elena Rodriguez", "David Kim"],
    duration: 142,
    type: "movie",
    seasons: null,
  },
  {
    id: "2",
    title: "Coffee & Hearts",
    year: 2024,
    genre: "Romance",
    rating: 7.8,
    synopsis: "A charming romantic comedy about two coffee shop owners who fall in love.",
    posterUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Sarah Mitchell",
    cast: ["Emma Thompson", "James Wilson", "Sofia Garcia"],
    duration: 108,
    type: "movie",
    seasons: null,
  },
  {
    id: "3",
    title: "Neural Storm",
    year: 2023,
    genre: "Sci-Fi",
    rating: 8.5,
    synopsis: "In a world where consciousness can be digitized, a hacker discovers a conspiracy that threatens humanity.",
    posterUrl: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Alex Turner",
    cast: ["Ryan Chen", "Maya Patel", "Jackson Brooks"],
    duration: 156,
    type: "movie",
    seasons: null,
  },
  {
    id: "4",
    title: "Midnight Shadows",
    year: 2024,
    genre: "Horror",
    rating: 7.2,
    synopsis: "A psychological horror film that blurs the line between dreams and nightmares.",
    posterUrl: "https://images.unsplash.com/photo-1507924538820-ede94a04019d?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Horror Master",
    cast: ["Lily Anderson", "Michael Torres", "Jessica Wong"],
    duration: 118,
    type: "movie",
    seasons: null,
  },
  {
    id: "5",
    title: "The Last Echo",
    year: 2023,
    genre: "Drama",
    rating: 9.1,
    synopsis: "A powerful drama about family, memory, and the stories that define us.",
    posterUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Maria Santos",
    cast: ["Anthony Hopkins", "Viola Davis", "Oscar Isaac"],
    duration: 134,
    type: "movie",
    seasons: null,
  },
  {
    id: "6",
    title: "Mountain Quest",
    year: 2024,
    genre: "Adventure",
    rating: 8.3,
    synopsis: "An epic adventure about a team of climbers attempting to summit an uncharted peak.",
    posterUrl: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Mountain Master",
    cast: ["Chris Hemsworth", "Zoe Saldana", "Tom Hardy"],
    duration: 128,
    type: "movie",
    seasons: null,
  },
];

export const mockTVShows: Movie[] = [
  {
    id: "tv1",
    title: "Digital Crown",
    year: 2024,
    genre: "Drama",
    rating: 9.2,
    synopsis: "A tech thriller series exploring power, corruption, and the price of innovation.",
    posterUrl: "https://images.unsplash.com/photo-1560472355-536de3962603?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Tech Director",
    cast: ["Benedict Cumberbatch", "Rami Malek", "Claire Foy"],
    duration: 60,
    type: "tv",
    seasons: 3,
  },
  {
    id: "tv2",
    title: "Code Blue",
    year: 2023,
    genre: "Medical",
    rating: 8.7,
    synopsis: "A medical drama following the lives of doctors in a cutting-edge hospital.",
    posterUrl: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Medical Director",
    cast: ["Ellen Pompeo", "Sandra Oh", "Patrick Dempsey"],
    duration: 45,
    type: "tv",
    seasons: 5,
  },
  {
    id: "tv3",
    title: "Realm of Echoes",
    year: 2024,
    genre: "Fantasy",
    rating: 9.0,
    synopsis: "An epic fantasy series set in a world where magic and technology collide.",
    posterUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Fantasy Director",
    cast: ["Kit Harington", "Emilia Clarke", "Peter Dinklage"],
    duration: 70,
    type: "tv",
    seasons: 2,
  },
  {
    id: "tv4",
    title: "Night Detective",
    year: 2023,
    genre: "Crime",
    rating: 8.4,
    synopsis: "A crime drama following a detective who solves cases that others can't.",
    posterUrl: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Crime Director",
    cast: ["Idris Elba", "Ruth Wilson", "Tom Hiddleston"],
    duration: 50,
    type: "tv",
    seasons: 4,
  },
  {
    id: "tv5",
    title: "Office Chronicles",
    year: 2024,
    genre: "Comedy",
    rating: 8.1,
    synopsis: "A workplace comedy that finds humor in the mundane world of corporate life.",
    posterUrl: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Comedy Director",
    cast: ["Steve Carell", "Mindy Kaling", "John Krasinski"],
    duration: 30,
    type: "tv",
    seasons: 6,
  },
  {
    id: "tv6",
    title: "Wild Earth",
    year: 2024,
    genre: "Documentary",
    rating: 9.5,
    synopsis: "A breathtaking documentary series exploring the world's most remote wilderness areas.",
    posterUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&w=400&h=600&fit=crop",
    director: "Nature Director",
    cast: ["David Attenborough"],
    duration: 60,
    type: "tv",
    seasons: 1,
  },
];

export const mockUserCommunities: UserCommunity[] = [
  {
    id: "1",
    userId: "user1",
    communityName: "Sci-Fi Enthusiasts",
    matchPercentage: 85,
    memberCount: 2847,
  },
  {
    id: "2",
    userId: "user1",
    communityName: "Drama Connoisseurs",
    matchPercentage: 78,
    memberCount: 1592,
  },
  {
    id: "3",
    userId: "user1",
    communityName: "Action Movie Fans",
    matchPercentage: 72,
    memberCount: 3241,
  },
  {
    id: "4",
    userId: "user1",
    communityName: "Independent Film Lovers",
    matchPercentage: 68,
    memberCount: 892,
  },
];

export const mockUserRatings: (UserRating & { movie: Movie })[] = [
  {
    id: "1",
    userId: "user1",
    movieId: "1",
    rating: 4,
    review: "Amazing action sequences and mind-bending plot!",
    createdAt: new Date("2024-01-15"),
    movie: mockMovies[0],
  },
  {
    id: "2",
    userId: "user1",
    movieId: "3",
    rating: 5,
    review: "Brilliant sci-fi thriller with incredible visuals.",
    createdAt: new Date("2024-01-10"),
    movie: mockMovies[2],
  },
  {
    id: "3",
    userId: "user1",
    movieId: "5",
    rating: 5,
    review: "Emotionally powerful and beautifully crafted.",
    createdAt: new Date("2024-01-08"),
    movie: mockMovies[4],
  },
];

export const mockWatchlist = [mockMovies[0], mockTVShows[0], mockMovies[4]];

export const genreData = [
  { name: "Sci-Fi", value: 32, color: "#1E40AF" },
  { name: "Drama", value: 28, color: "#8B5CF6" },
  { name: "Action", value: 24, color: "#F59E0B" },
  { name: "Thriller", value: 16, color: "#10B981" },
];

export const timelineData = [
  { month: "Jan", movies: 12 },
  { month: "Feb", movies: 19 },
  { month: "Mar", movies: 15 },
  { month: "Apr", movies: 25 },
  { month: "May", movies: 22 },
  { month: "Jun", movies: 18 },
];
